[server]
address = "0.0.0.0"
maxUploadSize = 10
[browser]
gatherUsageStats = false
[theme]
primaryColor = "#167D8D"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#EAF0F5"
textColor = "#172C40"
